# Generated by Django 3.1.6 on 2021-02-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vendor',
        ),
    ]
